describe 'Base64' do

  describe 'UIImage' do

    it 'should convert image data (PNG) to base64' do
      'test'.uiimage.nsdata.to_base64.should == 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAHgCAIAAADrGJBNAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAAaADAAQAAAABAAAB4AAAAAAnyqA0AAAAHGlET1QAAAACAAAAAAAAAPAAAAAoAAAA8AAAAPAAAABL2vm5UQAAABdJREFUSA1iuGvEwDCKR8NgNA0MyTQAAAAA///pNBr0AAAAFUlEQVRjuGvEwDCKR8NgNA0MyTQAAI2d/DCqzvXsAAAAAElFTkSuQmCC'
    end

  end

end
